# Generated by Django 5.1 on 2024-09-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('day_of_week', models.CharField(max_length=10, verbose_name='星期')),
                ('max_temperature', models.FloatField(verbose_name='最高气温')),
                ('min_temperature', models.FloatField(verbose_name='最低气温')),
                ('weather', models.CharField(max_length=50, verbose_name='天气')),
                ('wind_direction', models.CharField(max_length=50, verbose_name='风向')),
                ('wind_level', models.CharField(max_length=20, verbose_name='级别')),
            ],
            options={
                'verbose_name': '天气记录',
                'verbose_name_plural': '天气记录',
                'ordering': ['date'],
            },
        ),
    ]
